/*!
 * File generated by platform wizard. DO NOT MODIFY
 *
 */

metaonly module Platform inherits xdc.platform.IPlatform {

    config ti.platforms.generic.Platform.Instance CPU =
        ti.platforms.generic.Platform.create("CPU", {
            clockRate:      1000,                                       
            catalogName:    "ti.catalog.arm.cortexa8",
            deviceName:     "AM3359",
            customMemoryMap:
           [          
                ["SRAM", 
                     {
                        name: "SRAM",
                        base: 0x402f0400,                    
                        len: 0x0001fbff,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["DDR3", 
                     {
                        name: "DDR3",
                        base: 0x80000000,                    
                        len: 0x20000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
           ],

    });
    
instance :
    
    override config string codeMemory  = "SRAM";   
    override config string dataMemory  = "SRAM";                                
    override config string stackMemory = "SRAM";

}
