/*!
 * File generated by platform wizard. DO NOT MODIFY.
 *
 */

function getCpuDataSheet(cpuId)
{
    return this.$module.CPU.getCpuDataSheet(cpuId);
}

function getCreateArgs()
{
    return this.$module.CPU;
}

function getExeContext(prog)
{
    return this.$module.CPU.getExeContext(prog);
}


function getExecCmd(prog)
{
    return this.$module.CPU.getExecCmd(prog);
}


function getLinkTemplate(prog)
{
    return this.$module.CPU.getLinkTemplate(prog);
}


